# Generated by Django 6.0.7 on 2026-08-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=150)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_url', models.URLField(default='/accounts/signup/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
